In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [3]:
np.add(a, b)

array([5, 7, 9])

In [15]:
c = np.subtract(a,b)

In [7]:
np.multiply(a, b)

array([ 4, 10, 18])

In [8]:
np.divide(b, a)

array([4. , 2.5, 2. ])

In [9]:
np.power(a, 3)

array([ 1,  8, 27])

In [10]:
np.square(b)

array([16, 25, 36])

In [14]:
np.mod(a, 3)

array([1, 2, 0])

In [16]:
np.abs(c)

array([3, 3, 3])

In [17]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [22]:
d = np.array([10, 100, 1000])
e=np.log(d)
e

array([2.30258509, 4.60517019, 6.90775528])

In [23]:
np.exp(e)

array([  10.,  100., 1000.])

## random.seed

In [68]:
np.random.seed(1)
a = np.random.normal(10, 5, 10)
b = np.random.rand(2,3,3)
c = np.random.random((3, 1))

In [69]:
b

array([[[0.02738759, 0.67046751, 0.4173048 ],
        [0.55868983, 0.14038694, 0.19810149],
        [0.80074457, 0.96826158, 0.31342418]],

       [[0.69232262, 0.87638915, 0.89460666],
        [0.08504421, 0.03905478, 0.16983042],
        [0.8781425 , 0.09834683, 0.42110763]]])

In [70]:
c

array([[0.95788953],
       [0.53316528],
       [0.69187711]])

In [71]:
a

array([18.12172682,  6.94121793,  7.35914124,  4.63515689, 14.32703815,
       -1.50769348, 18.72405882,  6.1939655 , 11.59519548,  8.75314812])

In [72]:
b+c

array([[[0.98527712, 1.62835704, 1.37519433],
        [1.09185511, 0.67355222, 0.73126677],
        [1.49262168, 1.66013869, 1.00530129]],

       [[1.65021215, 1.83427868, 1.85249619],
        [0.6182095 , 0.57222007, 0.7029957 ],
        [1.57001962, 0.79022395, 1.11298474]]])

In [73]:
arr = np.array([[1, 2], [3, 4]])

In [81]:
np.mean(arr, axis=0)

array([2., 3.])