# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1, 23, 21])

# Create a 2-dimensional NumPy array using np.array()
array2 = np.array([[25, 23, 9], [4, 12, 7]])

# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([[[2, 6, 12], [21, 9, 8]], [[24, 70, 21], [12, 15, 20]], [[7, 9, 1],[2, 19, 12]]])

array([[[ 2,  6, 12],
        [21,  9,  8]],

       [[24, 70, 21],
        [12, 15, 20]],

       [[ 7,  9,  1],
        [ 2, 19, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1, array1.shape, array1.size, type(array1), array1.ndim, array1.dtype

(array([ 1, 23, 21]), (3,), 3, numpy.ndarray, 1, dtype('int64'))

In [11]:
# Attributes of 2-dimensional array
array2, array2.shape, array2.ndim, array2.dtype, type(array2)

(array([[25, 23,  9],
        [ 4, 12,  7]]),
 (2, 3),
 2,
 dtype('int64'),
 numpy.ndarray)

In [13]:
# Attributes of 3-dimensional array
array3, array3.shape, array3.ndim, array3.dtype, array3.size, type(array3)

(array([[[ 2,  6, 12],
         [21,  9,  8]],
 
        [[24, 70, 21],
         [12, 15, 20]],
 
        [[ 7,  9,  1],
         [ 2, 19, 12]]]),
 (3, 2, 3),
 3,
 dtype('int64'),
 18,
 numpy.ndarray)

In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(array2)
df

0   1  2
0  25  23  9
1   4  12  7

In [21]:
# Create an array of shape (10, 2) with only ones
onesA = np.ones(shape=(10, 2))
onesA, onesA.dtype

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 dtype('float64'))

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
zerosA = np.zeros(shape=(7, 2, 3))
zerosA

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
# Create an array within a range of 0 and 100 with step 3
arrayR1 = np.arange(0, 100, 3)
arrayR1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [44]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arrayR2 = np.random.randint(0, 10, size=(7,2))
arrayR2

array([[5, 4],
       [0, 5],
       [2, 6],
       [1, 9],
       [5, 4],
       [2, 0],
       [1, 9]])

In [45]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arrayF = np.random.random((3, 5))
arrayF

array([[0.79633907, 0.6136304 , 0.70103955, 0.90266678, 0.5281917 ],
       [0.0664996 , 0.33103474, 0.0381798 , 0.16228578, 0.15342349],
       [0.1961223 , 0.97727996, 0.17073645, 0.12480977, 0.98155102]])

In [49]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arrayR3 = np.random.randint(10, size=(4,6))
arrayR3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [54]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arrayV = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
arrayV, np.unique(arrayV)

(array([[7, 9, 3, 7, 1, 4, 4],
        [5, 7, 7, 4, 7, 3, 6],
        [2, 9, 5, 6, 4, 7, 9]]),
 array([1, 2, 3, 4, 5, 6, 7, 9]))

In [56]:
# Find the 0'th index of the latest array you created
arrayV[0]

array([7, 9, 3, 7, 1, 4, 4])

In [59]:
# Get the first 2 rows of latest array you created
arrayV[:2]

array([[7, 9, 3, 7, 1, 4, 4],
       [5, 7, 7, 4, 7, 3, 6]])

In [68]:
# Get the first 2 values of the first 2 rows of the latest array
arrayV[:2, :2]

array([[7, 9],
       [5, 7]])

In [76]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(42)
randomArray = np.random.randint(0,10, size=(3,5))
randomOnes = np.ones(shape=(3,5))
randomArray, randomOnes

(array([[6, 3, 7, 4, 6],
        [9, 2, 6, 7, 4],
        [3, 7, 7, 2, 5]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [80]:
# Add the two arrays together
addedArray = randomArray+randomOnes
addedArray

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [81]:
# Create another array of ones of shape (5, 3)
randomOnesAnother = np.ones(shape=(5, 3))
randomOnesAnother

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
# Try add the array of ones and the other most recent array together
newArray = randomOnesAnother+addedArray

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [88]:
#Transposing array to change the shape from (5,3) to (3,5)

In [89]:
transposedArray = randomOnesAnother.transpose()

In [90]:
newArray = addedArray+transposedArray
newArray

array([[ 8.,  5.,  9.,  6.,  8.],
       [11.,  4.,  8.,  9.,  6.],
       [ 5.,  9.,  9.,  4.,  7.]])

In [91]:
# Create another array of ones of shape (3, 5)
anotherOnes = np.ones(shape=(3, 5))

In [92]:
# Subtract the new array of ones from the other most recent array
subtractedArray = newArray-anotherOnes
subtractedArray

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [94]:
# Multiply the ones array with the latest array
multipliedArray = np.multiply(subtractedArray, anotherOnes)
multipliedArray

array([[ 7.,  4.,  8.,  5.,  7.],
       [10.,  3.,  7.,  8.,  5.],
       [ 4.,  8.,  8.,  3.,  6.]])

In [98]:
# Take the latest array to the power of 2 using '**'
squaredArray = multipliedArray**2
squaredArray

array([[ 49.,  16.,  64.,  25.,  49.],
       [100.,   9.,  49.,  64.,  25.],
       [ 16.,  64.,  64.,   9.,  36.]])

In [100]:
# Do the same thing with np.square()
squaredArray2 = np.square(multipliedArray)
squaredArray2

array([[ 49.,  16.,  64.,  25.,  49.],
       [100.,   9.,  49.,  64.,  25.],
       [ 16.,  64.,  64.,   9.,  36.]])

In [101]:
# Find the mean of the latest array using np.mean()
meanArray = np.mean(squaredArray)
meanArray

42.6

In [102]:
# Find the maximum of the latest array using np.max()
np.max(squaredArray)

100.0

In [103]:
# Find the minimum of the latest array using np.min()
np.min(squaredArray)

9.0

In [104]:
# Find the standard deviation of the latest array
np.std(squaredArray)

25.27924049491994

In [105]:
# Find the variance of the latest array
np.var(squaredArray)

639.0400000000001

In [107]:
# Reshape the latest array to (3, 5, 1)
transpose = squaredArray.reshape(3, 5, 1)
transpose

array([[[ 49.],
        [ 16.],
        [ 64.],
        [ 25.],
        [ 49.]],

       [[100.],
        [  9.],
        [ 49.],
        [ 64.],
        [ 25.]],

       [[ 16.],
        [ 64.],
        [ 64.],
        [  9.],
        [ 36.]]])

In [109]:
# Transpose the latest array
transpose.T

array([[[ 49., 100.,  16.],
        [ 16.,   9.,  64.],
        [ 64.,  49.,  64.],
        [ 25.,  64.,   9.],
        [ 49.,  25.,  36.]]])

What does the transpose do?

In [117]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(10, size=(3,3))
a2 = np.random.randint(10, size=(3,2))
a1, a2

(array([[7, 3, 1],
        [5, 5, 9],
        [3, 5, 1]]),
 array([[9, 1],
        [9, 3],
        [7, 6]]))

In [118]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2)
np.dot(a1, a2)

array([[ 97,  22],
       [153,  74],
       [ 79,  24]])

In [119]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a3 = np.random.randint(10, size=(4,3))
a4 = np.random.randint(10, size=(4,3))
a3, a4

(array([[8, 7, 4],
        [1, 4, 7],
        [9, 8, 8],
        [0, 8, 6]]),
 array([[8, 7, 0],
        [7, 7, 2],
        [0, 7, 2],
        [2, 0, 4]]))

In [120]:
# Perform a dot product on the two newest arrays you created
a3.dot(a4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [122]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a5 = a4.T
np.dot(a3, a5)

array([[113, 113,  57,  32],
       [ 36,  49,  42,  30],
       [128, 135,  72,  50],
       [ 56,  68,  68,  24]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [131]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(42)
a6 = np.random.randint(10, size=(3, 3))
a7 = np.random.randint(10, size=(3,3))
a6, a7

(array([[6, 3, 7],
        [4, 6, 9],
        [2, 6, 7]]),
 array([[4, 3, 7],
        [7, 2, 5],
        [4, 1, 7]]))

In [132]:
# Compare the two arrays with '>'
a6>a7

array([[ True, False, False],
       [False,  True,  True],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [133]:
# Compare the two arrays with '>='
a6>=a7

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True,  True]])

In [134]:
# Find which elements of the first array are greater than 7
a6>7

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [135]:
# Which parts of each array are equal? (try using '==')
a6==a7

array([[False,  True,  True],
       [False, False, False],
       [False, False,  True]])

In [138]:
# Sort one of the arrays you just created in ascending order
np.sort(a6)

array([[3, 6, 7],
       [4, 6, 9],
       [2, 6, 7]])

In [144]:
a7

array([[4, 3, 7],
       [7, 2, 5],
       [4, 1, 7]])

In [145]:
# Sort the indexes of one of the arrays you just created
np.argsort(a7, axis=1)

array([[1, 0, 2],
       [1, 2, 0],
       [1, 0, 2]])

In [147]:
np.argsort(a7, axis=0)

array([[0, 2, 1],
       [2, 1, 0],
       [1, 0, 2]])

In [148]:
#Finding modulo
mod = a6%2
mod

array([[1, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [149]:
#Exponential and logarithmics
np.exp(a7), np.log(a7)

(array([[  54.59815003,   20.08553692, 1096.63315843],
        [1096.63315843,    7.3890561 ,  148.4131591 ],
        [  54.59815003,    2.71828183, 1096.63315843]]),
 array([[1.38629436, 1.09861229, 1.94591015],
        [1.94591015, 0.69314718, 1.60943791],
        [1.38629436, 0.        , 1.94591015]]))

In [151]:
#Magic Function
%timeit sum(a7) 
%timeit np.sum(a7)

2.23 μs ± 6.77 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.95 μs ± 15 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [152]:
a7

array([[4, 3, 7],
       [7, 2, 5],
       [4, 1, 7]])

In [153]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a7)

2

In [154]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a7)

7

In [155]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a7, axis=1)

array([2, 0, 2])

In [156]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a7, axis=0)

array([0, 2, 1])

In [162]:
# Create an array of normally distributed random numbers
normalArray = np.random.randn(3, 5)
normalArray

array([[-0.71530371,  0.67959775, -0.73036663,  0.21645859,  0.04557184],
       [-0.65160035,  2.14394409,  0.63391902, -2.02514259,  0.18645431],
       [-0.66178646,  0.85243333, -0.79252074, -0.11473644,  0.50498728]])

In [163]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.